Repository openshift/ansible-service-broker, pull requests merged in 2018-02, with the labels that each got.

#758 Add a mailing list subscribe badge
  README.md
Labels: size/XS

#672 Remove minishift docs and link to golden source
  README.md
  docs/minishift.md
Labels: do-not-merge/blocked-paths, size/M

#754 Bug 1541461 - Deal with buggy encoded scopes from service catalog.
  pkg/broker/types.go
  pkg/clients/openshift.go
  pkg/handler/handler.go
Labels: 3.10, bug, needs-review, size/S

#755 Bug 1541461 - Deal with buggy encoded scopes from service catalog.
  pkg/broker/types.go
  pkg/clients/openshift.go
  pkg/handler/handler.go
Labels: 3.9, bug, needs-review, size/S

#747 Add lowercase proxy vars to spawned pods
  pkg/apb/executor.go
  pkg/apb/types.go
Labels: size/M

#759 adding sprint139 images for 1.0 release CI
  scripts/broker-ci/setup.sh
Labels: bug, size/XS

#756 Bug 1541461 - Deal with buggy encoded scopes from service catalog.
  pkg/broker/types.go
  pkg/clients/openshift.go
  pkg/handler/handler.go
Labels: bug, needs-review

#760 Fix the CI for release-1.0
  scripts/broker-ci/local-ci.sh
  scripts/broker-ci/postgresql.yaml
  scripts/travis.sh
  templates/deploy-ansible-service-broker.template.yaml
Labels: size/XS

#761 Upgrading from ubuntu 14.04 is no longer needed
  scripts/travis.sh
Labels: size/XS

#762 Remove upgrade from Ubuntu 14.0 to 16.04
  scripts/travis.sh
Labels: size/XS

#750 Bug 1543521 - Fix async bind with job already in progress.
  pkg/apb/executor.go
  pkg/apb/types.go
  pkg/apb/types_test.go
  pkg/broker/binding_subscriber.go
  pkg/broker/broker.go
  pkg/broker/deprovision_subscriber.go
  pkg/broker/provision_subscriber.go
  pkg/broker/provision_subscriber_test.go
  pkg/broker/types.go
  pkg/broker/unbinding_subscriber.go
  pkg/broker/update_subscriber.go
  pkg/dao/dao.go
Labels: size/L, spec-compliance

#769 Warn the user when using an old client
  scripts/run_latest_build.sh
Labels: size/XS

#767 Lock down everything in branch to this release
  scripts/broker-ci/setup.sh
  templates/deploy-ansible-service-broker.template.yaml
Labels: size/XS

#770 Rel lockdown 1.1
  scripts/broker-ci/setup-cluster.sh
  templates/deploy-ansible-service-broker.template.yaml
Labels: size/XS

#768 Proposal for saving extracted credentials
  docs/proposals/extracted_credentials_saved_as_secrets.md
Labels: 3.10, needs-review, proposal, size/M

#766 Remove plan dao methods
  pkg/apb/types.go
  pkg/broker/broker.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
Labels: 3.10, feature, needs-review, size/L

#774 Bug 1539542 - return bindings_retrievable
  pkg/broker/broker.go
  pkg/broker/types.go
  pkg/broker/util.go
Labels: 3.9, bug

#776 Bug 1539542 - return bindings_retrievable
  pkg/broker/broker.go
  pkg/broker/types.go
  pkg/broker/util.go
Labels: 3.10, bug, size/M

#777 add namespace config to k8s deployment template
  templates/k8s-ansible-service-broker.yaml.j2
Labels: size/XS

#765 Fix last op endpoint unbind response
  pkg/broker/broker.go
  pkg/broker/unbinding_subscriber.go
  pkg/handler/handler.go
Labels: 3.10, needs-review, size/M

#779 rename file to be more consistent.
  pkg/apb/mock_executor.go
Labels: size/XS

#786 Lock asb-brew releaser to 3.9 branch
  .tito/releasers.conf
Labels: build, size/S

#788 Lock asb-brew releaser to 3.10 branch
  .tito/releasers.conf
Labels: size/S

#787 Lock asb-brew releaser to 3.8 branch
  .tito/releasers.conf
Labels: size/XS

#781 Filter everything when whitelist is empty
  docs/filtering_apbs.md
  pkg/registries/filter.go
  pkg/registries/filter_test.go
  pkg/registries/testdata/empty_whitelist.yaml
Labels: size/M

#792 Adds docs for installing the broker in minikube
  README.md
Labels: docs, size/M

#793 Bug 1549189 - Filter everything when whitelist is empty
  docs/filtering_apbs.md
  pkg/registries/filter.go
  pkg/registries/filter_test.go
  pkg/registries/testdata/empty_whitelist.yaml
Labels: size/M

#796 Temporarily link to minishift-addons fork
  README.md
Labels: size/XS

#791 Bug 1548311 - Return success on depro extcred miss
  pkg/broker/deprovision_subscriber.go
Labels: size/XS

#790 Bug 1548311 - Return success on depro extcred miss
  pkg/broker/deprovision_subscriber.go
Labels: bug, size/XS

#775 Save extracted credentials into a secret
  docs/proposals/extracted_credentials_saved_as_secrets.md
  pkg/apb/bind.go
  pkg/apb/deprovision.go
  pkg/apb/executor.go
  pkg/apb/ext_creds.go
  pkg/apb/mock_executor.go
  pkg/apb/provision.go
  pkg/apb/provision_or_update.go
  pkg/apb/unbind.go
  pkg/apb/update.go
  pkg/app/app.go
  pkg/broker/binding_subscriber.go
  pkg/broker/broker.go
  pkg/broker/deprovision_subscriber.go
  pkg/broker/deprovision_subscriber_test.go
  pkg/broker/jobs.go
  pkg/broker/provision_subscriber.go
  pkg/broker/provision_subscriber_test.go
  pkg/broker/types.go
  pkg/broker/unbinding_subscriber.go
  pkg/broker/update_subscriber.go
  pkg/broker/update_subscriber_test.go
  pkg/clients/kubernetes.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
  pkg/runtime/extracted_credentials.go
  pkg/runtime/runtime.go
Labels: 3.10, needs-review, size/XL

#794 Broker client vendor update
  glide.lock
  glide.yaml
  vendor/github.com/automationbroker/broker-client-go/.gitignore
  vendor/github.com/automationbroker/broker-client-go/Gopkg.lock
  vendor/github.com/automationbroker/broker-client-go/Gopkg.toml
  vendor/github.com/automationbroker/broker-client-go/README.md
  vendor/github.com/automationbroker/broker-client-go/artifacts/bundle.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/example/bundle-example.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/example/jobstate-example.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/example/servicebinding-example.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/example/serviceinstance-example.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/jobstate.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/servicebinding.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/serviceinstance.yml
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/clientset.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/doc.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/fake/doc.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/fake/register.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/scheme/doc.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/scheme/register.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/automationbroker.io_client.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/bundle.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/doc.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/doc.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/fake_automationbroker.io_client.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/fake_bundle.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/fake_jobstate.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/fake_servicebinding.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/fake/fake_serviceinstance.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/generated_expansion.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/jobstate.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/servicebinding.go
  vendor/github.com/automationbroker/broker-client-go/client/clientset/versioned/typed/automationbroker.io/v1/serviceinstance.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/interface.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/v1/bundle.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/v1/interface.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/v1/jobstate.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/v1/servicebinding.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/automationbroker.io/v1/serviceinstance.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/factory.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/generic.go
  vendor/github.com/automationbroker/broker-client-go/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/automationbroker/broker-client-go/client/listers/automationbroker.io/v1/bundle.go
  vendor/github.com/automationbroker/broker-client-go/client/listers/automationbroker.io/v1/expansion_generated.go
  vendor/github.com/automationbroker/broker-client-go/client/listers/automationbroker.io/v1/jobstate.go
  vendor/github.com/automationbroker/broker-client-go/client/listers/automationbroker.io/v1/servicebinding.go
  vendor/github.com/automationbroker/broker-client-go/client/listers/automationbroker.io/v1/serviceinstance.go
  vendor/github.com/automationbroker/broker-client-go/cmd/example/main.go
  vendor/github.com/automationbroker/broker-client-go/hack/custom-boilerplate.go.txt
  vendor/github.com/automationbroker/broker-client-go/hack/update-codegen.sh
  vendor/github.com/automationbroker/broker-client-go/hack/verify-codegen.sh
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/register.go
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/v1/doc.go
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/v1/register.go
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/v1/types.go
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/v1/zz_generated.deepcopy.go
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/pmezard/go-difflib/difflib/difflib_test.go
Labels: 3.10, size/XXL, vendor-update
