Repository openshift/ansible-service-broker, pull requests merged in 2018-03, with the labels that each got.

#802 Remove tmp note re: minishift-addon
  README.md
Labels: size/XS

#807 Bug 1550385 - Add .default to proxy docs NO_PROXY
  docs/proxy.md
Labels: size/XS

#806 Bug 1550385 - Add .default to proxy docs NO_PROXY
  docs/proxy.md
Labels: size/XS

#800 parameterize the 'ansible-service-broker' namespace w/ NAMESPACE var
  templates/deploy-ansible-service-broker.template.yaml
Labels: size/S

#805 Force canary image be built from master
  build/Dockerfile-canary
Labels: size/XS

#804 Force canary image be built from release-1.1
  build/Dockerfile-canary
Labels: size/XS

#803 Force canary image be built from release-1.0
  build/Dockerfile-canary
Labels: size/XS

#795 Broker client dao
  pkg/app/app.go
  pkg/broker/broker.go
  pkg/clients/clients.go
  pkg/clients/crd.go
  pkg/dao/crd/conversion.go
  pkg/dao/crd/dao.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
  templates/deploy-ansible-service-broker.template.yaml
  templates/k8s-ansible-service-broker.yaml.j2
Labels: 3.10, needs-review, size/XXL

#727 Initial pass at proposal to change subscribers
  docs/proposals/subscriber-fan-in-fan-out.md
Labels: needs-review, proposal, size/L

#814 Removing links to older fusor GH org
  README.md
  docs/README.md
  docs/apb_integration.md
Labels: size/S

#808 Adds Service Bundle contract document
  docs/README.md
  docs/service-bundle.md
Labels: docs, size/L

#816 parameterize dao:type. Defaults to etcd
  templates/deploy-ansible-service-broker.template.yaml
Labels: 3.10, build, size/XS

#810 Document the Broker's versioning strategy
  README.md
  docs/versioning.md
Labels: docs, size/M

#820 Add breadcrumbs to release notes
  scripts/release_notes.sh
Labels: size/XS, tech-debt

#826 adding a blank line to the help output
  Makefile
Labels: size/XS, tech-debt

#825 remove extra deletion of extracted credentials in broker package
  pkg/broker/unbinding_subscriber.go
Labels: size/XS

#827 Default to an open localregistry policy
  templates/deploy-ansible-service-broker.template.yaml
Labels: needs-review, size/XS

#829 Add a note to run latest about current user
  scripts/run_latest_build.sh
Labels: size/XS

#831 make headings smaller
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, tech-debt

#833 Bug 1554239 - overwriting job state that has been finished.
  pkg/broker/broker.go
Labels: size/S

#821 pass provision credentials during deprovision
  Makefile
  pkg/apb/executor.go
  pkg/apb/mock_executor.go
  pkg/broker/broker.go
  pkg/handler/handler.go
Labels: size/M

#830 Proposal for Helm Chart Registry Adapter
  docs/proposals/helm-charts.md
Labels: feature, needs-review, size/L

#809 APB state support
  docs/proposals/apb-state-support.md
Labels: 3.10, proposal, size/M

#836 Format nits
  docs/proposals/apb-state-support.md
Labels: docs, proposal, size/M

#837 Display Custom Error Message for the APB via termination-log
  pkg/apb/watch_pod.go
  pkg/broker/jobs.go
Labels: size/S

#844 Only grab the token the broker sa is using
  scripts/run_latest_k8s_build.sh
Labels: size/XS

#841 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: docs, size/M

#845 Reformatted
  CODE_OF_CONDUCT.md
Labels: size/XS

#842 minor updates to proposal to clarify a few points
  docs/proposals/apb-state-support.md
Labels: size/S

#832 make username available for APB in the serviceInstance
  docs/service-bundle.md
  pkg/broker/broker.go
  pkg/broker/types.go
  pkg/broker/util.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: feature, size/M

#849 Add dep to travis
  scripts/travis.sh
Labels: size/XS

#852 Bug 1558472 - Update openshift registry to use www-auth redirect header
  docs/config.md
  pkg/registries/adapters/openshift_adapter.go
Labels: size/M

#854 Use the correct versions
  Gopkg.lock
  Gopkg.toml
Labels: size/XS

#856 Use the latest ansible version in travis scripts
  scripts/broker-ci/setup-cluster.sh
  scripts/travis.sh
Labels: size/XS

#857 Remind the user to give the developer cluster-admin
  scripts/run_latest_build.sh
Labels: size/XS

#855 Warn in the logs that a spec failed to load and continue
  pkg/dao/crd/dao.go
Labels: size/XS

#863 make more than one stage for all the tasks we want to do.
  .travis.yml
  scripts/travis.sh
Labels: size/M

#838 make CRD the defaults for all templates
  scripts/openshift/deploy.sh
  scripts/prep_local_devel_env.sh
  scripts/run_latest_build.sh
  scripts/run_latest_k8s_build.sh
  templates/deploy-ansible-service-broker.template.yaml
  templates/deploy-local-dev-changes.yaml
  templates/k8s-ansible-service-broker.yaml.j2
  templates/k8s-local-dev-changes.yaml
Labels: feature, size/L

#862 Fix docs - enabling RBAC for minikube
  README.md
Labels: size/XS
