Repository openshift/ansible-service-broker, pull requests merged in 2018-09, with the labels that each got.

#1070 Bump bundle-lib release to 0.2.13
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/bundle/executor.go
Labels: size/S

#1072 Bug 1625809 - Accept quoted APB broker_destroy_shared_resources arg
  apb/tasks/dao_crd.yaml
  apb/tasks/main.yml
  apb/templates/broker-auth.clusterrolebinding.yaml
  apb/templates/broker-client.clusterrolebinding.yaml
  apb/templates/broker.clusterrolebinding.yaml
Labels: size/S

#1069 Add 2018-09-04 meeting notes
  docs/meetings/2018/asbroker.2018-09-04-13.45.html
  docs/meetings/2018/asbroker.2018-09-04-13.45.log.html
  docs/meetings/2018/asbroker.2018-09-04-13.45.log.txt
  docs/meetings/2018/asbroker.2018-09-04-13.45.txt
Labels: size/L

#1074 Bump bundle-lib release to 0.2.14
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/local_openshift_adapter.go
Labels: size/S

#1075 Disable keeping namespace on error in ASB
  apb/defaults/main.yml
Labels: size/XS

#1077 add operation and param validation
  test/last_operation_bind.sh
Labels: size/S

#1079 Prepare for 1.4 release
  README.md
  ansible-service-broker.spec
Labels: size/XS

#1080 Use the 4.0 releaser branch
  .tito/releasers.conf
Labels: size/XS

#1082 Update 1.2 copr releaser
  .tito/releasers.conf
Labels: size/XS

#1083 Update 1.3 copr releaser
  .tito/releasers.conf
Labels: size/XS

#1084 Add dockerfiles for old releases
  build/Dockerfile-v3.10
  build/Dockerfile-v3.11
Labels: size/M

#1085 [DO NOT MERGE] Disable travis kube until it can be fixed
  .travis.yml
Labels: size/XS

#1078 Add broker operator support
  Makefile
  ansible_role/.travis.yml
  ansible_role/apb.yml
  ansible_role/apb/Dockerfile
  ansible_role/apb/Dockerfile-latest
  ansible_role/apb/Dockerfile-nightly
  ansible_role/apb/README.md
  ansible_role/apb/install.yaml
  ansible_role/defaults/main.yml
  ansible_role/files/bundle.crd.yaml
  ansible_role/files/bundlebindings.crd.yaml
  ansible_role/files/bundleinstances.crd.yaml
  ansible_role/meta/main.yml
  ansible_role/operator/Dockerfile
  ansible_role/operator/cr.example.yaml
  ansible_role/operator/crd.yaml
  ansible_role/operator/deploy.yaml
  ansible_role/operator/rbac.yaml
  ansible_role/operator/watches.yaml
  ansible_role/playbooks/deprovision.yml
  ansible_role/playbooks/operator.yml
  ansible_role/playbooks/provision.yml
  ansible_role/playbooks/test.yml
  ansible_role/tasks/build_config.yml
  ansible_role/tasks/dao_crd.yml
  ansible_role/tasks/dao_etcd.yml
  ansible_role/tasks/generate_certificate.yml
  ansible_role/tasks/main.yml
  ansible_role/templates/broker-access.clusterrole.yaml
  ansible_role/templates/broker-auth.clusterrole.yaml
  ansible_role/templates/broker-auth.clusterrolebinding.yaml
  ansible_role/templates/broker-auth.secret.yaml
  ansible_role/templates/broker-client.clusterrolebinding.yaml
  ansible_role/templates/broker-client.secret.yaml
  ansible_role/templates/broker-client.serviceaccount.yaml
  ansible_role/templates/broker-redirector.route.yaml
  ansible_role/templates/broker-user-auth.clusterrole.yaml
  ansible_role/templates/broker.clusterrolebinding.yaml
  ansible_role/templates/broker.deployment.yaml
  ansible_role/templates/broker.namespace.yaml
  ansible_role/templates/broker.route.yaml
  ansible_role/templates/broker.service.yaml
  ansible_role/templates/broker.serviceaccount.yaml
  ansible_role/templates/broker.servicecatalog.yaml
  ansible_role/templates/etcd-auth.secret.yaml
  ansible_role/templates/etcd-ca.secret.yaml
  ansible_role/templates/etcd.deployment.yaml
  ansible_role/templates/etcd.pvc.yaml
  ansible_role/templates/etcd.service.yaml
  ansible_role/vars/config.yml
  ansible_role/vars/configmap.yml
  ansible_role/vars/main.yaml
  apb/templates/broker.configmap.yaml
  pkg/app/app.go
  scripts/deploy.sh
Labels: size/XL

#1086 Fix RPM build
  ansible-service-broker.spec
  downstream.patch
Labels: size/S

#1089 make the apb install the correct broker release
  ansible-service-broker.spec
Labels: size/XS

#1090 update rpm spec and add apb Dockerfiles
  ansible-service-broker.spec
  ansible_role/apb/Dockerfile-v3.10
  ansible_role/apb/Dockerfile-v3.11
Labels: size/L

#1091 Fix dockerfile typo
  build/Dockerfile-v3.11
Labels: size/XS

#1094 Fix 1.1 copr releaser
  .tito/releasers.conf
Labels: size/XS

#1093 add v3.9 Dockerfile
  build/Dockerfile-v3.9
Labels: size/S

#1088 backport apb to 1.2
  ansible-service-broker.spec
  apb/.travis.yml
  apb/Dockerfile
  apb/Dockerfile-latest
  apb/Dockerfile-nightly
  apb/README.md
  apb/apb.yml
  apb/defaults/main.yml
  apb/files/bundle.crd.yaml
  apb/files/bundlebindings.crd.yaml
  apb/files/bundleinstances.crd.yaml
  apb/install.yaml
  apb/meta/main.yml
  apb/playbooks/deprovision.yml
  apb/playbooks/provision.yml
  apb/playbooks/test.yml
  apb/tasks/dao_crd.yaml
  apb/tasks/dao_etcd.yaml
  apb/tasks/generate_certificate.yaml
  apb/tasks/main.yml
  apb/templates/broker-access.clusterrole.yaml
  apb/templates/broker-auth.clusterrole.yaml
  apb/templates/broker-auth.clusterrolebinding.yaml
  apb/templates/broker-auth.secret.yaml
  apb/templates/broker-client.clusterrolebinding.yaml
  apb/templates/broker-client.secret.yaml
  apb/templates/broker-client.serviceaccount.yaml
  apb/templates/broker-redirector.route.yaml
  apb/templates/broker-user-auth.clusterrole.yaml
  apb/templates/broker.clusterrolebinding.yaml
  apb/templates/broker.configmap.yaml
  apb/templates/broker.deployment.yaml
  apb/templates/broker.namespace.yaml
  apb/templates/broker.route.yaml
  apb/templates/broker.service.yaml
  apb/templates/broker.serviceaccount.yaml
  apb/templates/broker.servicecatalog.yaml
  apb/templates/etcd-auth.secret.yaml
  apb/templates/etcd-ca.secret.yaml
  apb/templates/etcd.deployment.yaml
  apb/templates/etcd.pvc.yaml
  apb/templates/etcd.service.yaml
  apb/vars/main.yaml
Labels: size/XXL

#1095 Fix v3.10 automation-broker-apb Dockerfile
  ansible_role/apb/Dockerfile-v3.10
Labels: size/XS

#1096 fix the broker url for v3.10 apb
  apb/templates/broker-access.clusterrole.yaml
  apb/templates/broker.servicecatalog.yaml
Labels: size/XS
