Repository openshift/ansible-service-broker, pull requests merged in 2018-04, with the labels that each got.

#870 Add migration command
  .gitignore
  Makefile
  ansible-service-broker.spec
  build/Dockerfile-canary
  build/Dockerfile-localdev
  cmd/migration/main.go
Labels: build, size/L

#881 Fix bug 1564542
  Gopkg.lock
  pkg/broker/broker.go
  vendor/github.com/automationbroker/bundle-lib/.gitignore
  vendor/github.com/automationbroker/bundle-lib/Makefile
  vendor/github.com/automationbroker/bundle-lib/apb/types.go
  vendor/github.com/automationbroker/bundle-lib/apb/types_test.go
Labels: size/XL

#883 Bug 1565648 - expose _apb_service_binding_id to bind role
  docs/service-bundle.md
  pkg/broker/broker.go
  pkg/broker/types.go
Labels: size/S

#885 Issue 882 - Simple broker template should use release-1.1 instead of a sprint tag
  templates/simple-broker-template.yaml
Labels: size/XS

#892 link broken - typo fixed
  docs/debugging.md
Labels: size/XS

#894 Point to v3.9.0 release of origin
  docs/versioning.md
Labels: size/XS

#886 Cfme poc
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/cfme_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
Labels: size/L

#903 Fix typo in run_latest_build.sh
  scripts/run_latest_build.sh
Labels: size/XS

#899 Bug 1567004 - Delete extracted credentials secret during synchronous unbind
  pkg/broker/broker.go
Labels: size/XS

#891 Update scripts to use the broker apb
  scripts/run_latest_build.sh
  scripts/run_latest_k8s_build.sh
Labels: needs-review, size/L

#897 Bug 1569220 - Add dashboard redirector feature
  .gitignore
  Gopkg.lock
  Makefile
  build/Dockerfile-localdev
  cmd/dashboard-redirector/README.md
  cmd/dashboard-redirector/main.go
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
  pkg/broker/jobs.go
  pkg/broker/jobs_test.go
  pkg/broker/types.go
  templates/deploy-ansible-service-broker.template.yaml
  vendor/github.com/automationbroker/broker-client-go/artifacts/bundle.yml
  vendor/github.com/automationbroker/broker-client-go/artifacts/serviceinstance.yml
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker.io/v1/types.go
  vendor/github.com/automationbroker/bundle-lib/Gopkg.lock
  vendor/github.com/automationbroker/bundle-lib/Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/apb/executor.go
  vendor/github.com/automationbroker/bundle-lib/apb/mock_executor.go
  vendor/github.com/automationbroker/bundle-lib/apb/testdata/alpha_apb.yml
  vendor/github.com/automationbroker/bundle-lib/apb/types.go
  vendor/github.com/automationbroker/bundle-lib/apb/types_test.go
  vendor/github.com/automationbroker/bundle-lib/crd/conversions.go
  vendor/github.com/automationbroker/bundle-lib/runtime/watch_pod.go
  vendor/github.com/automationbroker/bundle-lib/runtime/watch_pod_test.go
Labels: needs-review, size/XL

#904 fix statements with formatting
  pkg/app/app.go
  pkg/auth/auth.go
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
  pkg/broker/work_engine.go
  pkg/dao/crd/dao.go
  pkg/dao/etcd/dao.go
Labels: size/M, tech-debt

#905 Build migration into canary image
  ansible-service-broker.spec
  build/Dockerfile-canary
Labels: size/S

#906 Use git clone for canary
  build/Dockerfile-canary
Labels: size/XS

#898 Bug 1533425 - protect against simultaneous updates
  pkg/broker/broker.go
  pkg/broker/types.go
  pkg/dao/crd/dao.go
Labels: size/M

#910 Frustration release target
  Makefile
Labels: size/XS

#915 Lock helm version for ci
  scripts/broker-ci/setup-catalog.sh
Labels: size/S
