Repository openshift/ansible-service-broker, pull requests merged in 2018-12, with the labels that each got.

#1141 Add epoch to rpm spec
  ansible-service-broker.spec
Labels: approved, size/XS

#1142 Add epoch 1.3
  ansible-service-broker.spec
Labels: approved, needs-rebase, size/XS

#1146 Fix caBundle population for 4.0 deploys
  ansible_role/tasks/main.yml
  ansible_role/templates/broker-service-ca-bundle.configmap.yaml
  ansible_role/templates/broker.servicecatalog.yaml
Labels: approved, lgtm, size/S

#1147 Check if ca-bundle configmap already exists to avoid contention with cert-signer operator
  ansible_role/tasks/main.yml
Labels: approved, lgtm, size/XS

#1150 Update operator playbook to use IMAGE from environment
  ansible_role/playbooks/operator.yml
Labels: approved, lgtm, size/S

#1152 Fix downstream container builds
  ansible_role/operator/Dockerfile
Labels: approved, lgtm, size/XS

#1154 Add Dockerfile link to prepare for automated downstream builds
  ansible_role/Dockerfile.operator.ocp
Labels: approved, lgtm, size/XS

#1153 Make it possible to run tests only
  ansible_role/apb/test_manifest.yaml
  ansible_role/playbooks/test.yml
Labels: approved, lgtm, size/M
