Repository openshift/ansible-service-broker, pull requests merged in 2018-11, with the labels that each got.

#1126 Operator should use meta from AO
  ansible_role/playbooks/operator.yml
Labels: lgtm, size/XS

#1127 Set OLM_MANAGED to true by default in the operator Dockerfile
  ansible_role/operator/Dockerfile
Labels: size/XS

#1128 add operator linting and openshift CI make tasks
  Makefile
  ansible_role/handlers/main.yml
  ansible_role/tasks/build_config.yml
  ansible_role/tasks/main.yml
  build/Dockerfile-openshift
Labels: size/M

#1129 Automation Broker meeting 20181113
  docs/meetings/2018/asbroker.2018-11-13-15.00.html
  docs/meetings/2018/asbroker.2018-11-13-15.00.log.html
  docs/meetings/2018/asbroker.2018-11-13-15.00.log.txt
  docs/meetings/2018/asbroker.2018-11-13-15.00.txt
Labels: size/L

#1131 Fix operator lint task in openshift CI
  Makefile
Labels: approved, lgtm, size/XS

#1132 Add jmontleon to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1134 Add djzager to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1133 Clean up .travis.yml and remove duplicate tests
  .travis.yml
Labels: approved, lgtm, size/S
