Repository openshift/ansible-service-broker, pull requests merged in 2018-07, with the labels that each got.

#998 Update docs for helm adapter
  docs/config.md
Labels: size/S

#1000 Use docker cp instead of mounting host volume
  .travis.yml
  Makefile
  apb/Dockerfile
  apb/tasks/main.yml
Labels: size/S

#990 Use broker-apb test playbook to test the broker
  .travis.yml
  Makefile
  apb/playbooks/test.yml
  apb/tasks/main.yml
  apb/vars/main.yaml
Labels: do-not-merge/hold, size/L

#1005 Simple ci
  .travis.yml
  Makefile
Labels: size/S

#1004 Automation Broker meeting 7/10/2018
  docs/meetings/2018/asbroker.2018-07-10-13.33.html
  docs/meetings/2018/asbroker.2018-07-10-13.33.log.html
  docs/meetings/2018/asbroker.2018-07-10-13.33.log.txt
  docs/meetings/2018/asbroker.2018-07-10-13.33.txt
Labels: size/XL

#1013 Fix default APB_IMAGE
  scripts/deploy.sh
Labels: size/XS

#1014 Broker apb rpm
  ansible-service-broker.spec
  apb/Dockerfile-latest
  apb/Dockerfile-nightly
Labels: size/S

#1015 Add ns broker support to the broker's apb
  apb/tasks/main.yml
  apb/templates/broker-access.clusterrole.yaml
  apb/templates/broker.servicecatalog.yaml
  apb/vars/main.yaml
Labels: size/S

#1012 Add tag to the ASB registry configuration doc
  docs/config.md
Labels: size/XS

#1008 Enhance spec reconciliation, using async bootstrap
  Gopkg.lock
  Gopkg.toml
  pkg/broker/broker.go
  pkg/broker/broker_test.go
  pkg/broker/testdata/specs.json
  pkg/broker/testdata/updatedSpecs.json
  pkg/dao/crd/dao.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
  pkg/dao/mock_dao.go
  pkg/dao/mocks/Dao.go
  pkg/handler/handler.go
  pkg/metrics/metrics.go
  vendor/github.com/automationbroker/broker-client-go/pkg/apis/automationbroker/v1alpha1/types.go
  vendor/github.com/automationbroker/bundle-lib/bundle/secrets.go
  vendor/github.com/automationbroker/bundle-lib/bundle/types.go
  vendor/github.com/automationbroker/bundle-lib/crd/conversions.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/galaxy_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: size/XXL

#1019 Automation Broker Community meeting 2018-07-24
  docs/meetings/2018/asbroker.2018-07-24-13.31.html
  docs/meetings/2018/asbroker.2018-07-24-13.31.log.html
  docs/meetings/2018/asbroker.2018-07-24-13.31.log.txt
  docs/meetings/2018/asbroker.2018-07-24-13.31.txt
Labels: size/XL

#1022 include FQName in spec logging, ID isn't useful enough
  pkg/broker/broker.go
  pkg/dao/crd/dao.go
Labels: size/S

#1020 Improve logging when wait_for_broker fails
  apb/install.yaml
  apb/tasks/main.yml
  apb/vars/main.yaml
  scripts/deploy.sh
Labels: size/M

#954 update obj form definition
  pkg/broker/util.go
  pkg/broker/util_test.go
Labels: 3.11 | release-1.3, bug, size/M

#1021 Add namespaced broker docs
  docs/README.md
  docs/namespaced-brokers.md
Labels: size/L

#1016 Add galaxy adapter
  apb/defaults/main.yml
  apb/tasks/main.yml
  apb/templates/broker.configmap.yaml
  docs/config.md
Labels: size/M

#1002 update for quay adapter
  apb/defaults/main.yml
  apb/templates/broker.configmap.yaml
  docs/config.md
  pkg/app/app.go
Labels: size/M

#1023 Update galaxy-adapter to include galaxy URL
  Gopkg.lock
  Gopkg.toml
  apb/defaults/main.yml
  vendor/github.com/automationbroker/bundle-lib/bundle/types.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/dockerhub_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/galaxy_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
Labels: size/L
