Repository openshift/ansible-service-broker, pull requests merged in 2018-08, with the labels that each got.

#1025 Set new location for service-broker-ci git repo
  Makefile
Labels: size/XS

#1026 remove newline from version log
  pkg/app/app.go
Labels: size/XS

#1027 Bug 1577797 - call flag...Parse to prevent logging error
  cmd/broker/main.go
Labels: 3.11 | release-1.3, bug, size/XS

#1030 Bug 1583587 - lower loglevel to debug, wrap others
  pkg/dao/crd/dao.go
Labels: 3.11 | release-1.3, bug, size/S

#1032 Bug 1583503 Always run updates
  pkg/broker/broker.go
  pkg/handler/handler.go
Labels: size/S

#1033 Add route timeout annotation
  apb/templates/broker.route.yaml
Labels: size/XS

#1039 Add mock for the call to DeleteExtractedCredential
  pkg/broker/job_state_subscriber_test.go
Labels: size/M

#1029 Standardize broker endpoints
  apb/tasks/generate_certificate.yaml
  apb/templates/broker-access.clusterrole.yaml
  apb/templates/broker.configmap.yaml
  apb/templates/broker.service.yaml
  apb/templates/broker.servicecatalog.yaml
  docs/config.md
  pkg/app/app.go
  pkg/broker/broker.go
Labels: size/M

#1038 fix coverage to fail when tests fail
  Makefile
  pkg/util/logging/logger_test.go
  pkg/util/logging/testdata/logging_config_test.yaml
Labels: size/M

#1040 Bug 1599522 - Include skip_verify_tls doc info for registries
  docs/config.md
Labels: size/S

#1043 Fix broker route to line up with service
  apb/templates/broker-redirector.route.yaml
  apb/templates/broker.deployment.yaml
  apb/templates/broker.route.yaml
  apb/templates/broker.service.yaml
  build/Dockerfile-canary
Labels: size/S

#1045 Update bundle-lib
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/bundle/ext_creds.go
  vendor/github.com/automationbroker/bundle-lib/bundle/provision.go
  vendor/github.com/automationbroker/bundle-lib/bundle/update.go
  vendor/github.com/automationbroker/bundle-lib/metrics/metrics.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/local_openshift_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: size/L

#1034 Bug 1583049 - Add bundle-lib metrics registration
  pkg/app/app.go
Labels: size/XS

#1046 Fix broker install yaml for release-1.2
  apb/install.yaml
Labels: size/XS

#1050 Bug 1610714 - pass bindingid to unbind jobs
  pkg/broker/jobs.go
  pkg/broker/jobs_test.go
Labels: size/L

#1048 Bug 1615787 - Add APB Spec to Broker APB
  ansible-service-broker.spec
  apb/Dockerfile
  apb/Dockerfile-latest
  apb/Dockerfile-nightly
  apb/apb.yml
  apb/defaults/main.yml
  downstream.patch
Labels: size/L

#1051 Bug 1615723 - check for not found ext creds
  pkg/broker/broker.go
Labels: size/XS

#1052 Add 2018-08-21 meeting notes
  docs/meetings/2018/asbroker.2018-08-21-13.30.html
  docs/meetings/2018/asbroker.2018-08-21-13.30.log.html
  docs/meetings/2018/asbroker.2018-08-21-13.30.log.txt
  docs/meetings/2018/asbroker.2018-08-21-13.30.txt
Labels: size/XL

#1053 Fix broker rpm spec
  ansible-service-broker.spec
Labels: size/S

#1055 Update source0 in rpm spec
  ansible-service-broker.spec
Labels: size/XS

#1057 Bug 1615787 - Make a registry configurable via apb
  apb/Dockerfile
  apb/Dockerfile-latest
  apb/Dockerfile-nightly
  apb/apb.yml
  apb/defaults/main.yml
  apb/playbooks/test.yml
  apb/templates/broker.configmap.yaml
Labels: size/L

#1060 Check for capabilities instead of openshift during APB install
  .travis.yml
  apb/defaults/main.yml
  apb/playbooks/test.yml
  apb/tasks/dao_etcd.yaml
  apb/tasks/main.yml
  apb/templates/broker-auth.clusterrole.yaml
  apb/templates/broker.configmap.yaml
  apb/templates/broker.deployment.yaml
  apb/templates/broker.namespace.yaml
  apb/templates/broker.service.yaml
  apb/templates/broker.servicecatalog.yaml
  apb/templates/etcd.deployment.yaml
  apb/templates/etcd.service.yaml
Labels: size/L

#1063 Fix downstream patch for capabilities check
  downstream.patch
Labels: size/XS

#1064 use the new osb prefix
  test/bind.sh
  test/bootstrap.sh
  test/catalog.sh
  test/deprovision.sh
  test/getbind.sh
  test/getinstance.sh
  test/last_operation.sh
  test/last_operation_bind.sh
  test/provision.sh
  test/unbind.sh
Labels: size/S

#1065 Update bundle-lib to 0.2.11
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go
Labels: size/L

#1066 Default to NOT deleting shared broker resources
  apb/defaults/main.yml
  apb/tasks/dao_crd.yaml
  apb/tasks/main.yml
Labels: size/S

#1067 Prevent deprovision of brokers with instances
  apb/defaults/main.yml
  apb/tasks/main.yml
Labels: size/S
