Repository openshift/ansible-service-broker, pull requests merged in 2018-06, with the labels that each got.

#975 Make ci should not do deployment
  .travis.yml
  Makefile
Labels: size/XS

#976 Bug 1585649 - wait group should be added to before go function
  pkg/broker/work_engine.go
Labels: size/XS

#977 Bug 1585649 - wait group should be added to before go function
  pkg/broker/work_engine.go
Labels: size/XS

#978 Travis should run only for master/release branches
  .travis.yml
Labels: size/XS

#980 reformat tables to be readable without rendering
  docs/config.md
Labels: 3.11 | release-1.3, docs, size/M

#909 Ensure initial state set when job started. Reduce repition in job definitions. Allow jobs to be mocked out at broker level
  pkg/app/app.go
  pkg/broker/broker.go
  pkg/broker/jobs.go
  pkg/broker/jobs_test.go
  pkg/broker/types.go
  pkg/broker/work_engine.go
  pkg/broker/work_engine_test.go
  pkg/dao/dao.go
  pkg/dao/mock_dao.go
Labels: 3.11 | release-1.3, size/XL

#987 Fix deployment stage
  .travis.yml
Labels: size/S

#988 Remove tag from deployment
  .travis.yml
Labels: size/S

#983 adding unit tests for broker package
  pkg/broker/broker_test.go
  pkg/broker/job_state_subscriber_test.go
  pkg/broker/jobs_test.go
  pkg/dao/dao.go
  pkg/dao/mocks/Dao.go
Labels: 3.11 | release-1.3, size/XL, tech-debt

#991 Pass in namespace to runtime
  pkg/app/app.go
  pkg/broker/broker_test.go
Labels: size/S

#985 Add hostname to test scripts
  test/bind.sh
  test/bootstrap.sh
  test/catalog.sh
  test/deprovision.sh
  test/getbind.sh
  test/getinstance.sh
  test/last_operation.sh
  test/last_operation_bind.sh
  test/provision.sh
  test/unbind.sh
Labels: size/M

#993 Use travis_tag on tag builds
  .travis.yml
  Makefile
Labels: size/S

#994 Login for deploy on tag
  .travis.yml
Labels: size/S

#926 Support building a debuggable image for development
  .gitignore
  CONTRIBUTING.md
  Makefile
  build/Dockerfile-canary
  build/Dockerfile-localdev
  build/dev-entrypoint.sh
  scripts/clean_debug_env.sh
  scripts/prep_debug_env.sh
Labels: 3.11 | release-1.3, size/L

#989 adds docs and plumbing for the skip_verify_tls setting on the rhcc adapter
  docs/config.md
  pkg/app/app.go
Labels: size/M
