Repository openshift/ansible-service-broker, pull requests merged in 2018-05, with the labels that each got.

#918 Update AA to APB in docs
  docs/design.md
  docs/meetings/20170119-minutes.txt
Labels: size/S

#921 Add install.yaml for release-1.0 broker
  apb/install.yaml
Labels: size/M

#923 Run the apb in a different project
  apb/install.yaml
Labels: size/S

#927 Bug 1572129 - remove unnecessary SetState
  pkg/broker/broker.go
  pkg/dao/crd/dao.go
Labels: bug, size/L

#924 Bug 1572470 - use binding id as instance, do not error on conflict
  pkg/broker/broker.go
  pkg/dao/crd/dao.go
  pkg/handler/handler.go
Labels: 3.10, bug, size/M

#929 Add fix for get si npe
  pkg/broker/broker.go
Labels: size/S

#930 Spell check a bunch of items
  CONTRIBUTING.md
  README.md
  docs/debugging.md
  docs/design.md
  docs/secrets.md
  docs/service-bundle.md
  pkg/app/app.go
  pkg/auth/auth.go
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
  pkg/broker/types.go
  pkg/dao/crd/dao.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
  pkg/dao/filters.go
  pkg/fusortest/util.go
  pkg/handler/handler.go
  pkg/mock/dao.go
  pkg/version/apbruntimeversion.go
  pkg/version/apbversion.go
  scripts/prep_local_devel_env.sh
  templates/k8s-variables.yaml
Labels: size/M, tech-debt

#933 Allow Automation Broker to be useful when used as a dependency
  cmd/broker/main.go
  pkg/app/app.go
Labels: size/L

#937 bump bundle-lib to 0.1.5
  Gopkg.lock
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry_test.go
Labels: size/L, vendor-update

#922 Add install.yaml for release-1.1 broker
  apb/install.yaml
Labels: size/M

#942 Bug 1550418 - Return op token on depro in progress
  pkg/handler/handler.go
Labels: bug, size/XS

#944 lock the version of deploy template to correct branch
  scripts/run_latest_build.sh
Labels: size/XS

#940 doc to show how to use broker via vendor
  docs/using_as_library.md
Labels: docs, size/L

#949 Bug 1577144 - fixing logging so it is more clear
  pkg/broker/broker.go
Labels: 3.10 | release-1.2, size/XS

#947 Bug 1576728 - Fixes multiple requests to a CR
  Gopkg.lock
  pkg/dao/crd/dao.go
  pkg/dao/etcd/dao.go
  vendor/github.com/automationbroker/bundle-lib/apb/types.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter_test.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
Labels: 3.10 | release-1.2, size/L

#952 Update release dates in README
  README.md
Labels: 3.11 | release-1.3, size/XS

#950 add partner rhcc adapter documentation
  docs/config.md
Labels: 3.10 | release-1.2, size/S

#955 Bump version for next release
  .tito/releasers.conf
  ansible-service-broker.spec
Labels: size/XS

#959 Bug 1578319 - send _apb* parameters to unbind
  pkg/broker/broker.go
Labels: size/S

#960 Bug 1578319 - send _apb* parameters to unbind
  pkg/broker/broker.go
Labels: size/S

#956 Replace latest with release-1.2
  scripts/broker-ci/setup-cluster.sh
  scripts/openshift/deploy.sh
  scripts/run_latest_build.sh
  scripts/run_latest_k8s_build.sh
  templates/deploy-ansible-service-broker.template.yaml
  templates/k8s-variables.yaml
Labels: size/S

#961 Switch from go-logging to logrus
  Gopkg.lock
  Gopkg.toml
  pkg/app/app.go
  pkg/auth/auth.go
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
  pkg/broker/jobs.go
  pkg/broker/types.go
  pkg/broker/work_engine.go
  pkg/dao/crd/dao.go
  pkg/dao/dao.go
  pkg/dao/etcd/dao.go
  pkg/handler/handler.go
  pkg/metrics/metrics.go
  pkg/util/logging/logger.go
  pkg/util/logging/logger_test.go
  vendor/github.com/op/go-logging/CONTRIBUTORS
  vendor/github.com/op/go-logging/LICENSE
  vendor/github.com/op/go-logging/backend.go
  vendor/github.com/op/go-logging/format.go
  vendor/github.com/op/go-logging/level.go
  vendor/github.com/op/go-logging/log_nix.go
  vendor/github.com/op/go-logging/log_windows.go
  vendor/github.com/op/go-logging/logger.go
  vendor/github.com/op/go-logging/memory.go
  vendor/github.com/op/go-logging/multi.go
  vendor/github.com/op/go-logging/syslog.go
  vendor/github.com/op/go-logging/syslog_fallback.go
Labels: 3.11 | release-1.3, size/XXL, tech-debt

#935 Add requested parameters when not in existing service instance
  pkg/broker/broker.go
Labels: 3.11 | release-1.3, needs-review, size/S

#966 Bug 1581580 - skip if bind instance does not have credentials
  cmd/migration/main.go
Labels: size/S

#967 add v3.10 install method to README
  README.md
  docs/images/oc-enable.gif
Labels: size/S

#971 Bug 1583064 - missing action causes many sandboxes
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
Labels: 3.10 | release-1.2, bug, size/M

#972 Bug 1583064 - missing action causes many sandboxes
  pkg/broker/broker.go
  pkg/broker/job_state_subscriber.go
Labels: 3.11 | release-1.3, bug, size/M

#939 Add Broker APB source to project
  .travis.yml
  Makefile
  apb/.travis.yml
  apb/Dockerfile
  apb/README.md
  apb/apb.yml
  apb/defaults/main.yml
  apb/files/bundle.crd.yaml
  apb/files/bundlebindings.crd.yaml
  apb/files/bundleinstances.crd.yaml
  apb/install.yaml
  apb/meta/main.yml
  apb/playbooks/deprovision.yml
  apb/playbooks/provision.yml
  apb/playbooks/test.yml
  apb/tasks/dao_crd.yaml
  apb/tasks/dao_etcd.yaml
  apb/tasks/generate_certificate.yaml
  apb/tasks/main.yml
  apb/templates/broker-access.clusterrole.yaml
  apb/templates/broker-auth.clusterrole.yaml
  apb/templates/broker-auth.clusterrolebinding.yaml
  apb/templates/broker-auth.secret.yaml
  apb/templates/broker-client.clusterrolebinding.yaml
  apb/templates/broker-client.secret.yaml
  apb/templates/broker-client.serviceaccount.yaml
  apb/templates/broker-redirector.route.yaml
  apb/templates/broker.clusterrolebinding.yaml
  apb/templates/broker.configmap.yaml
  apb/templates/broker.deployment.yaml
  apb/templates/broker.namespace.yaml
  apb/templates/broker.route.yaml
  apb/templates/broker.service.yaml
  apb/templates/broker.serviceaccount.yaml
  apb/templates/broker.servicecatalog.yaml
  apb/templates/etcd-auth.secret.yaml
  apb/templates/etcd-ca.secret.yaml
  apb/templates/etcd.deployment.yaml
  apb/templates/etcd.pvc.yaml
  apb/templates/etcd.service.yaml
  apb/vars/main.yaml
  scripts/broker-ci/cleanup-ci.sh
  scripts/broker-ci/error.sh
  scripts/broker-ci/gather-logs.sh
  scripts/broker-ci/pv-setup.sh
  scripts/broker-ci/setup-broker.sh
  scripts/broker-ci/setup-catalog.sh
  scripts/broker-ci/setup-cluster.sh
  scripts/broker-ci/setup-minikube.sh
  scripts/broker-ci/wait-for-resource.sh
  scripts/deploy.sh
  scripts/kubernetes/deploy.sh
  scripts/kubernetes/resources.sh
  scripts/openshift/deploy.sh
  scripts/openshift/resources.sh
  scripts/run_latest_build.sh
  scripts/run_latest_k8s_build.sh
  scripts/travis.sh
Labels: 3.11 | release-1.3, needs-review, size/XXL
