Repository openshift/ansible-service-broker, pull requests merged in 2018-10, with the labels that each got.

#1099 Automation broker meeting logs 10/02/2018
  docs/meetings/2018/asbroker.2018-10-02-13.31.html
  docs/meetings/2018/asbroker.2018-10-02-13.31.log.html
  docs/meetings/2018/asbroker.2018-10-02-13.31.log.txt
  docs/meetings/2018/asbroker.2018-10-02-13.31.txt
Labels: size/XL

#1100 Fix canary, use same tag for canary/nightly broker and apb's
  ansible_role/apb/Dockerfile-canary
  ansible_role/apb/Dockerfile-nightly
Labels: size/S

#1101 Fix Makefile
  Makefile
Labels: size/XS

#1104 Fix deploy template default value for Broker URL
  templates/deploy-ansible-service-broker.template.yaml
Labels: needs-rebase, size/XS

#1109 💚 Get golint changed upstream.
  .travis.yml
Labels: size/XS

#1107 trying to fix travis
  .travis.yml
  scripts/broker-ci/setup-cluster.sh
  scripts/travis.sh
Labels: size/S

#1106 Additional OLM support
  ansible_role/operator/cr.example.yaml
  ansible_role/tasks/main.yml
  ansible_role/templates/broker.deployment.yaml
Labels: size/M

#1108 Use 3.11 instead of latest for ansible-service-broker image
  ansible_role/operator/Dockerfile
Labels: size/XS

#1119 Fix release 1.3 kube tests
  Makefile
  scripts/deploy.sh
Labels: size/XS

#1115 Use the correct golint url (release-1.2)
  Makefile
  scripts/travis.sh
Labels: 3.10 | release-1.2, size/S

#1120 fix 1.2 auto escalate setting
  scripts/run_latest_k8s_build.sh
Labels: size/XS

#1121 Update networkpolicy permissions for kubernetes
  apb/templates/broker-auth.clusterrole.yaml
Labels: size/XS

#1122 Fix 1.2 ci log collection
  scripts/broker-ci/gather-logs.sh
Labels: size/XS

#1111 Update to bundle-lib 0.2.15 to fix net-policy issue
  Gopkg.lock
  Gopkg.toml
  ansible_role/templates/broker-auth.clusterrole.yaml
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: 3.12 | release-1.4, size/L

#1112 Update to bundle-lib 0.2.15 to fix net-policy issue
  Gopkg.lock
  Gopkg.toml
  apb/templates/broker-auth.clusterrole.yaml
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: 3.11 | release-1.3, size/L

#1123 Fix golint in release-1.2
  scripts/travis.sh
Labels: size/XS

#1081 1062 - disallow the SAME UUID for instance and bindings
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: size/M

#1124 2018-10-30 Automation Broker IRC meeting logs
  docs/meetings/2018/asbroker.2018-10-30-14.03.html
  docs/meetings/2018/asbroker.2018-10-30-14.03.log.html
  docs/meetings/2018/asbroker.2018-10-30-14.03.log.txt
  docs/meetings/2018/asbroker.2018-10-30-14.03.txt
Labels: size/L

#1125 Remove unused asbcli.
  scripts/asbcli/README.md
  scripts/asbcli/asbcli
  scripts/asbcli/pod-preset.yaml
  scripts/asbcli/requirements.txt
  scripts/asbcli/secret.yaml
Labels: size/XL
