Repository openshift/ansible-service-broker, pull requests merged in 2019-12, with the labels that each got.

#1263 fix CI builds (#1262)
  build/custom-ci-build-root.Dockerfile
Labels: approved, size/XS

#1261 Bug 1782058: Allow ASBO to access endpoints
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
  operator/roles/ansible-service-broker/templates/broker-operator.monitor-role.yaml.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1260 Bug 1776135: Allow ASBO to access endpoints
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
  operator/roles/ansible-service-broker/templates/broker-operator.monitor-role.yaml.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1264 Bug 1782058: make labels match the metrics endpoint
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1265 Bug 1776135: make labels match the metrics endpoint
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1266 Bug 1782058: fix the service monitor selector
  operator/roles/ansible-service-broker/templates/broker-operator.service-monitor.yaml.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1267 Bug 1776135: fix the service monitor selector
  operator/roles/ansible-service-broker/templates/broker-operator.service-monitor.yaml.j2
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1258 Bug 1772743: Add olm.skipRange to all CSVs and art.yaml (#1257)
  build/custom-ci-build-root.Dockerfile
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
