Repository openshift/ansible-service-broker, pull requests merged in 2019-08, with the labels that each got.

#1241 Bug 1696113 add oauth and skip_verify_ssl support
  Gopkg.lock
  Gopkg.toml
  docs/config.md
  pkg/app/app.go
  vendor/github.com/automationbroker/bundle-lib/Gopkg.lock
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/dockerhub_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client_test.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/rhcc_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/rhcc_adapter_test.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
Labels: approved, lgtm, size/XL

#1240 fix Etherpad and Bindable database service diagrams
  docs/usecases.md
Labels: approved, lgtm, ok-to-test, size/XS

#1245 add SDK team to broker OWNERS
  OWNERS
Labels: approved, lgtm, size/S
