Repository openshift/ansible-service-broker, pull requests merged in 2019-01, with the labels that each got.

#1157 Update operator Dockerfile to use AO master, add subresource in CRD
  ansible_role/operator/Dockerfile
  ansible_role/operator/crd.yaml
Labels: approved, lgtm, size/XS

#1158 Check for truthy since these values are always defined
  ansible_role/playbooks/operator.yml
Labels: approved, lgtm, size/XS

#1156 Revert "Add ASB operator deployment manifest assets."
  manifests/00-asb-namespace.yaml
  manifests/01-asb-catalogsource-configmap.yaml
  manifests/02-asb-catalogsource.yaml
  manifests/03-asb-operatorgroup.yaml
  manifests/04-asb-subscription.yaml
  manifests/05-asb-cr.yaml
  manifests/06-asb-clusterrolebinding.yaml
Labels: approved, size/L

#1159 Fix ansible assertion syntax
  ansible_role/playbooks/operator.yml
Labels: approved, size/XS

#1161 Add Derek to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#1160 Add csv
  operator/deploy/olm-catalog/ansible-service-broker-operator.csv.yaml
Labels: approved, size/L

#1162 Add install modes
  operator/deploy/olm-catalog/ansible-service-broker-operator.csv.yaml
Labels: approved, lgtm, size/XS

#1167 bundle-lib 0.2.16 release
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
Labels: approved, lgtm, size/M

#1168 Use old operator builds until new one stabalizes
  Makefile
Labels: approved, lgtm, size/S

#1170 Bump csv version
  operator/deploy/olm-catalog/0.2.0/automationbroker.crd.yaml
  operator/deploy/olm-catalog/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/0.2.0/bundle.crd.yaml
  operator/deploy/olm-catalog/0.2.0/bundlebindings.crd.yaml
  operator/deploy/olm-catalog/0.2.0/bundleinstances.crd.yaml
  operator/deploy/olm-catalog/automationbroker.package.yaml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker-service-ca-bundle.configmap.yaml.j2
  operator/roles/ansible-service-broker/templates/broker.deployment.yaml.j2
  operator/roles/ansible-service-broker/templates/broker.service.yaml.j2
  operator/roles/ansible-service-broker/templates/broker.servicecatalog.yaml.j2
Labels: approved, size/S

#1171 Add missing operator env vars
  operator/deploy/olm-catalog/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#1172 Explicitly set kubeconfig on lookups
  Makefile
  operator/roles/ansible-service-broker/handlers/main.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/tasks/validate_absent.yml
  operator/roles/ansible-service-broker/templates/broker.servicecatalog.yaml.j2
Labels: approved, lgtm, size/S
