Repository openshift/ansible-service-broker, pull requests merged in 2019-03, with the labels that each got.

#1186 bug 1684420: fixing name in the bundlebinding CRD
  operator/deploy/olm-catalog/0.2.0/bundlebindings.crd.yaml
Labels: approved, lgtm, size/XS

#1182 Update operator/role, show error message on misconfigured RBAC
  operator/roles/ansible-service-broker/tasks/main.yml
Labels: approved, lgtm, size/S

#1187 adding OLM testing file
  operator/build/olm-testing.Dockerfile
Labels: approved, lgtm, size/S

#1190 update csv to get the correct example for downstream images
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/1.0.0/openshiftansibleservicebroker.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#1191 Bug 1689787 -update image pull policy to ifNotPresent
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/1.0.0/openshiftansibleservicebroker.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#1194 Bug 1678158 - backport oauth2 support to rhcc
  pkg/app/app.go
  pkg/registries/adapters/adapter.go
  pkg/registries/adapters/oauth/client.go
  pkg/registries/adapters/oauth/client_test.go
  pkg/registries/adapters/rhcc_adapter.go
  pkg/registries/adapters/rhcc_adapter_test.go
  pkg/registries/registry.go
Labels: approved, lgtm, size/XL

#1195 Remove eriknelson from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1197 testing
  operator/build/molecule.Dockerfile
Labels: approved, lgtm, size/S

#1198 fix path for molecule binary in container
  operator/build/molecule.Dockerfile
Labels: approved, lgtm, size/XS

#1199 Make sure we can access the installed python libraries
  operator/build/entrypoint.sh
  operator/build/molecule.Dockerfile
Labels: approved, lgtm, size/S

#1200 adding custom build root
  build/custom-ci-build-root.Dockerfile
  operator/build/molecule.Dockerfile
Labels: approved, lgtm, size/M

#1201 Fabian cluster scenario
  operator/molecule/cluster/molecule.yml
  operator/molecule/cluster/playbook.yml
Labels: approved, lgtm, size/S

#1202 Bug 1693953 - Setting correct default for ASBs that are deployed with the operator.
  operator/roles/ansible-service-broker/defaults/main.yml
Labels: approved, lgtm, size/XS
