Repository openshift/ansible-service-broker, pull requests merged in 2019-02, with the labels that each got.

#1176 Adding 2018-11-27 meeting notes
  docs/meetings/2018/asbroker.2018-11-27-15.03.html
  docs/meetings/2018/asbroker.2018-11-27-15.03.log.html
  docs/meetings/2018/asbroker.2018-11-27-15.03.log.txt
  docs/meetings/2018/asbroker.2018-11-27-15.03.txt
Labels: approved, size/L

#1175 Use new operator
  Makefile
  ansible_role/Dockerfile.operator.ocp
  ansible_role/operator/Dockerfile
  ansible_role/operator/cr.example.yaml
  ansible_role/operator/crd.yaml
  ansible_role/operator/deploy.yaml
  ansible_role/operator/rbac.yaml
  ansible_role/operator/watches.yaml
  operator/Dockerfile.ocp
  operator/Dockerfile.rhel
  operator/playbook.yaml
Labels: approved, size/L

#1179 Bug 1643303 - only delete netpol if they exist
  pkg/runtime/runtime.go
Labels: approved, lgtm

#1180 Bug 1643303 - Fixed in bundle-lib 0.2.17
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: approved, size/M

#1181 Bug 1643303 - Fixed in bundle-lib 0.2.17
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
Labels: approved, size/M

#1184 Update CSV based on community-operators PR
  operator/deploy/olm-catalog/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#1185 Bug 1643303 - Fixed in bundle-lib 0.1.10
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/apb/executor.go
  vendor/github.com/automationbroker/bundle-lib/apb/provision_or_update.go
  vendor/github.com/automationbroker/bundle-lib/apb/secrets.go
  vendor/github.com/automationbroker/bundle-lib/apb/types.go
  vendor/github.com/automationbroker/bundle-lib/clients/crd.go
  vendor/github.com/automationbroker/bundle-lib/clients/kubernetes.go
  vendor/github.com/automationbroker/bundle-lib/clients/openshift.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/dockerhub_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/local_openshift_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/mock_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/rhcc_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
  vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go
  vendor/github.com/automationbroker/bundle-lib/runtime/watch_pod.go
  vendor/github.com/automationbroker/bundle-lib/runtime/watch_pod_test.go
Labels: approved, size/L
