Repository openshift/ansible-service-broker, pull requests merged in 2019-07, with the labels that each got.

#1234 Bug 1723422 - fix pagination url, bump bundle-lib
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/clients/kubernetes.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
Labels: approved, lgtm, size/M

#1237 Pass *_PROXY envvars on to ASB deployment
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
  operator/roles/ansible-service-broker/templates/broker.deployment.yaml.j2
Labels: approved, lgtm, size/XS

#1238 Bug 1732557: Fixing CSV validations
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1239 Bug 1732559: Fixing CSV validations for the CVP checks
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
