Repository openshift/ansible-service-broker, pull requests merged in 2019-06, with the labels that each got.

#1226 Bug 1717623 - 4.1.0 -> 4.1.1
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
  operator/molecule/cluster-olm/prepare.yml
Labels: approved, lgtm, size/XS

#1227 Bug 1692281 - Adding service monitor permissions if monitoring is installed
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker.monitor-role.yaml.j2
  operator/roles/ansible-service-broker/templates/broker.monitor-rolebinding.yaml.j2
Labels: approved, lgtm, size/M

#1228 Adding art replacement file
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, lgtm, size/S

#1229 bug 1717623 - 4.1.1 -> 4.1.2
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
  operator/molecule/cluster-olm/prepare.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1230 typo in the current csv version
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, lgtm, size/XS

#1225 adding UBI dockerfile
  build/Dockerfile-ubi
  build/entrypoint.sh
  operator/roles/ansible-service-broker/templates/broker-config.configmap.yaml.j2
Labels: approved, lgtm, size/S

#1231 adding 4.2 csv and updating package and art files
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/automationbroker.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundle.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundlebindings.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundleinstances.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/image-references
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
  operator/molecule/cluster-olm/molecule.yml
  operator/molecule/cluster-olm/prepare.yml
Labels: approved, lgtm, size/L

#1232 Bug 1721161: cherry-pick art.yaml to 4.1 release
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1233 Bug 1721161: Fix typo art.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
