Repository openshift/ansible-service-broker, pull requests merged in 2019-11, with the labels that each got.

#1249 Run user_setup if it's still present
  operator/build/Dockerfile
Labels: approved, lgtm, size/XS

#1250 Add alert to fire when broker is installed.
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/automationbroker.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/bundle.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/bundlebindings.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/bundleinstances.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/image-references
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
  operator/molecule/cluster-olm/molecule.yml
  operator/molecule/cluster-olm/prepare.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker.prometheus-alert.yaml.j2
Labels: approved, lgtm, size/L

#1247 Bug 1763005 - add registry-proxy support, bump bundle-lib
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go
  vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
  vendor/github.com/automationbroker/bundle-lib/registries/registry.go
Labels: approved, kind/bug, lgtm, size/M

#1256 Allow ASBO metrics to be scraped.
  Makefile
  operator/deploy/namespace.yaml
  operator/deploy/operator.yaml
  operator/deploy/service_account.yaml
  operator/molecule/cluster-olm/playbook.yml
  operator/molecule/cluster/playbook.yml
  operator/molecule/cluster/verify.yml
  operator/roles/ansible-service-broker/defaults/main.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker-operator.monitor-role.yaml.j2
  operator/roles/ansible-service-broker/templates/broker-operator.monitor-rolebinding.yaml.j2
  operator/roles/ansible-service-broker/templates/broker-operator.service-monitor.yaml.j2
  operator/roles/ansible-service-broker/templates/broker.prometheus-alert.yaml.j2
Labels: approved, lgtm, size/L

#1257 Bug 1772392: Add olm.skipRange to all CSVs and art.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
