Repository openshift/ansible-service-broker, pull requests merged in 2019-04, with the labels that each got.

#1205 wait for service catalog during cluster CI test
  operator/molecule/cluster/prepare.yml
Labels: approved, lgtm, size/S

#1204 Bug 1692281 - operator should deploy a service-monitor
  operator/roles/ansible-service-broker/defaults/main.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker.service-monitor.yaml.j2
  operator/roles/ansible-service-broker/templates/prometheus.role.yaml.j2
  operator/roles/ansible-service-broker/templates/prometheus.role_binding.yaml.j2
Labels: approved, lgtm, size/M

#1207 Properly configure and gate service monitor deployment behind an option
  docs/operator.md
  operator/roles/ansible-service-broker/defaults/main.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker.service-monitor.yaml.j2
  operator/roles/ansible-service-broker/templates/prometheus.role.yaml.j2
  operator/roles/ansible-service-broker/templates/prometheus.role_binding.yaml.j2
Labels: approved, lgtm, size/M

#1208 Adding ability to deploy ASB with OLM and csv to test.
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/molecule/cluster-olm/e2e-olm.sh
  operator/molecule/cluster-olm/molecule.yml
  operator/molecule/cluster-olm/playbook.yml
  operator/molecule/cluster-olm/prepare.yml
  operator/molecule/cluster/prepare.yml
Labels: approved, lgtm, size/L

#1209 Adding ASB e2e functional tests
  operator/molecule/cluster-olm/playbook.yml
  operator/molecule/cluster-olm/prepare.yml
  operator/molecule/cluster/molecule.yml
  operator/molecule/cluster/playbook.yml
  operator/molecule/cluster/verify.yml
Labels: approved, lgtm, size/L

#1211 bump version to v1
  operator/deploy/crds/osb_v1_automationbroker_cr.yaml
  operator/deploy/crds/osb_v1_automationbroker_crd.yaml
  operator/deploy/olm-catalog/automationbroker-manifests/0.2.0/automationbroker.crd.yaml
  operator/deploy/olm-catalog/automationbroker-manifests/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/automationbroker.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/molecule/cluster-olm/playbook.yml
  operator/molecule/cluster/playbook.yml
  operator/molecule/cluster/prepare.yml
  operator/molecule/cluster/verify.yml
  operator/molecule/test-cluster/playbook.yml
  operator/molecule/test-local/playbook.yml
  operator/molecule/test-local/prepare.yml
  operator/molecule/test-local/verify.yml
  operator/roles/ansible-service-broker/tasks/main.yml
  operator/roles/ansible-service-broker/templates/broker.automationbroker.yaml.j2
  operator/watches.yaml
Labels: approved, lgtm, size/M

#1214 Release pipeline file name changes
  operator/build/olm-testing.downstream.Dockerfile
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/automationbroker.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/bundle.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/bundlebindings.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/bundleinstances.crd.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/image-references
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
  operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
  operator/molecule/cluster-olm/e2e-olm.sh
  operator/molecule/cluster-olm/molecule.yml
  operator/molecule/cluster-olm/prepare.yml
Labels: approved, size/M

#1215 Fixing CI custom build root
  build/custom-ci-build-root.Dockerfile
Labels: approved, lgtm, size/XS
